### ISSUE TITLE
clear input fields after saving

### ISSUE THREAD

**Issue by flashback2k14** [lyio/socobo-inventory#13]
please clear all inputs in socobo-inventory-create.html after successful saving. if i want to add a new item. the old is still there.

**Comment by flashback2k14** [comment]
![bug](https://cloud.githubusercontent.com/assets/6609359/9970920/b393cba4-5e58-11e5-9aa6-417cdace240f.PNG)

measurement, date, and category not cleared!

**Comment by lyio** [comment]
Please create a separate issue for that in YouTrack, not here
